const constants = {
  ANSWER_QUESTION: 'ANSWER_QUESTIONS',
  AUTH_USER: 'AUTH_USER',
  ADD_ANSWER_TO_USER: 'ADD_ANSWER_TO_USER',
  ADD_QUESTION_TO_USER: 'ADD_QUESTION_TO_USER',
  UPDATE_USER: 'UPDATE_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  RECEIVE_QUESTIONS: 'RECEIVE_QUESTIONS',
}

export default constants